# Day 4: Giant Squid

## Part 1

You're already almost 1.5km (almost a mile) below the surface of the ocean, already so deep that you can't see any sunlight. What you can see, however, is a giant squid that has attached itself to the outside of your submarine.

Maybe it wants to play bingo?

Bingo is played on a set of boards each consisting of a 5x5 grid of numbers. Numbers are chosen at random, and the chosen number is marked on all boards on which it appears. (Numbers may not appear on all boards.) If all numbers in any row or any column of a board are marked, that board wins. (Diagonals don't count.)

The submarine has a bingo subsystem to help passengers (currently, you and the giant squid) pass the time. It automatically generates a random order in which to draw numbers and a random set of boards (your puzzle input). For example:
```
7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7
 ```
After the first five numbers are drawn (7, 4, 9, 5, and 11), there are no winners, but the boards are marked as follows (shown here adjacent to each other to save space):

<pre>
22 13 17 <b>11</b>  0         3 15  0  2 22        14 21 17 24  <b>4</b>
 8  2 23 <b> 4</b> 24        <b> 9</b> 18 13 17 <b> 5</b>        10 16 15 <b> 9</b> 19
21 <b> 9</b> 14 16 <b> 7</b>        19  8 <b> 7</b> 25 23        18  8 23 26 20
 6 10  3 18 <b> 5</b>        20 <b>11</b> 10 24 <b> 4</b>        22 <b>11</b> 13  6 <b> 5</b>
 1 12 20 15 19        14 21 16 12  6         2  0 12  3 <b> 7</b>
</pre>

After the next six numbers are drawn (17, 23, 2, 0, 14, and 21), there are still no winners:
<pre>
22 13 <b>17</b> <b>11</b> <b> 0</b>         3 15 <b> 0</b> <b> 2</b> 22        <b>14</b> <b>21</b> <b>17</b> 24  <b>4</b>
 8 <b> 2</b> <b>23</b> <b> 4</b> 24        <b> 9</b> 18 13 <b>17</b> <b> 5</b>        10 16 15 <b> 9</b> 19
<b>21</b> <b> 9</b> <b>14</b> 16 <b> 7</b>        19  8 <b> 7</b> 25 <b>23</b>        18  8 <b>23</b> 26 20
 6 10  3 18 <b> 5</b>        20 <b>11</b> 10 24 <b> 4</b>        22 <b>11</b> 13  6 <b> 5</b>
 1 12 20 15 19        <b>14</b> <b>21</b> 16 12  6        <b> 2</b> <b> 0</b> 12  3 <b> 7</b>
</pre>

Finally, 24 is drawn:
<pre>
22 13 <b>17</b> <b>11</b> <b> 0</b>         3 15 <b> 0</b> <b> 2</b> 22        <b>14</b> <b>21</b> <b>17</b> <b>24</b>  <b>4</b>
 8 <b> 2</b> <b>23</b> <b> 4</b> <b>24</b>        <b> 9</b> 18 13 <b>17</b> <b> 5</b>        10 16 15 <b> 9</b> 19
<b>21</b> <b> 9</b> <b>14</b> 16 <b> 7</b>        19  8 <b> 7</b> 25 <b>23</b>        18  8 <b>23</b> 26 20
 6 10  3 18 <b> 5</b>        20 <b>11</b> 10 <b>24</b> <b> 4</b>        22 <b>11</b> 13  6 <b> 5</b>
 1 12 20 15 19        <b>14</b> <b>21</b> 16 12  6        <b> 2</b> <b> 0</b> 12  3 <b> 7</b>
</pre>
At this point, the third board wins because it has at least one complete row or column of marked numbers (in this case, the entire top row is marked: 14 21 17 24 4).

The score of the winning board can now be calculated. Start by finding the sum of all unmarked numbers on that board; in this case, the sum is 188. Then, multiply that sum by the number that was just called when the board won, 24, to get the final score, 188 * 24 = 4512.

To guarantee victory against the giant squid, figure out which board will win first. What will your final score be if you choose that board?

In [1]:
import numpy as np

In [2]:
class Board:

    def __init__(self, data):
        self.data = data
        self.marked = np.zeros(data.shape,dtype=None)
        
        
    def update_scoreboard(self, number):
        inds = np.where(self.data == number)
        #print(self.data)
        #print(inds)
        #print(number)
        self.marked[inds]=1
        #print(self.marked)
        
    def is_winner(self):
        rows = np.sum(self.marked,1)
        cols = np.sum(self.marked,0)
        #print(rows,cols)
        if np.any(rows == 5) or np.any(cols == 5):
            return True
        else:
            return False
    def final_score(self, number):
        #print(self.data)
        #print(self.marked)
        #print(number)
        inds = np.where(self.marked == 0)
        score = 0
        #print(np.sum(self.data[inds]))
        score = np.sum(self.data[inds])*number
       
        return score
    
    def remove_board(self):
        del self
    
    


In [3]:
def load_boards(path):
    file = open(path, "r")
    lines = file.readlines()
    lines = [l.strip("\n\n") for l in lines]
    #print(lines)
    numbers= list(map(int, lines[0].split(",")))
    boards: list[Board] = []
    rows = []

    for l in lines[1:]:
        if len(l) == 0:
            continue
    
        l = l.split(" ")
        l = [int(j) for j in l if len(j) > 0]


        rows.append(l)

        if len(rows) == 5:
            rows = np.asarray(rows)
            boards.append(Board(rows))
            rows = []
        
        
    return numbers, boards

In [4]:
[numbers, boards] = load_boards("day04_data_test.txt")

In [5]:
print(numbers)

[7, 4, 9, 5, 11, 17, 23, 2, 0, 14, 21, 24, 10, 16, 13, 6, 15, 25, 12, 22, 18, 20, 8, 19, 3, 26, 1]


In [6]:
#for b in boards:
#    print(b.data)
#    print(b.marked)

In [7]:
#for b in boards:
#    b.is_winner()

In [8]:
for n in numbers:
    for b in boards:
        b.update_scoreboard(n)
        if b.is_winner():
            print("winner found")
            print(b.data)
            print(b.marked)
            print("Final Score:", b.final_score(n))
            break
    else:
        # Continue if the inner loop wasn't broken.
        continue
    # Inner loop was broken, break the outer.
    break
    

winner found
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]
 [1. 1. 0. 0. 1.]]
Final Score: 4512


In [9]:
[numbers, boards] = load_boards("day04_data.txt")

In [10]:
for n in numbers:
    for b in boards:
        b.update_scoreboard(n)
        if b.is_winner():
            print("winner found after number ", n)
            print(b.data)
            print(b.marked)
            print("Final Score:", b.final_score(n))
            break
    else:
        # Continue if the inner loop wasn't broken.
        continue
    # Inner loop was broken, break the outer.
    break

winner found after number  48
[[63  3 22  7 10]
 [36 76 14 77 38]
 [48 27 40  9 60]
 [31 56 75 74 78]
 [86 64 71 90 67]]
[[0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Final Score: 44736


In [11]:
def winning_board(numbers, boards):
    for n in numbers:
        for b in boards:
            b.update_scoreboard(n)
            if b.is_winner():
                print("winner found after number ", n)
                print(b.data)
                print(b.marked)
                print("Final Score:", b.final_score(n))
                break
        else:
            # Continue if the inner loop wasn't broken.
            continue
        # Inner loop was broken, break the outer.
        break

In [12]:
[numbers, boards] = load_boards("day04_data_test.txt")
winning_board(numbers, boards)

winner found after number  24
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]
 [1. 1. 0. 0. 1.]]
Final Score: 4512


In [13]:
[numbers, boards] = load_boards("day04_data.txt")
winning_board(numbers, boards)

winner found after number  48
[[63  3 22  7 10]
 [36 76 14 77 38]
 [48 27 40  9 60]
 [31 56 75 74 78]
 [86 64 71 90 67]]
[[0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Final Score: 44736


## Part 2

On the other hand, it might be wise to try a different strategy: let the giant squid win.

You aren't sure how many bingo boards a giant squid could play at once, so rather than waste time counting its arms, the safe thing to do is to figure out which board will win last and choose that one. That way, no matter which boards it picks, it will win for sure.

In the above example, the second board is the last to win, which happens after 13 is eventually called and its middle column is completely marked. If you were to keep playing until this point, the second board would have a sum of unmarked numbers equal to 148 for a final score of 148 * 13 = 1924.

Figure out which board will win last. Once it wins, what would its final score be?

In [14]:
def losing_board(numbers, boards):
    
    #step through each of the called numbers
    for n in numbers:
        
        #create a copy of the avaliable boards in order to remove winning boards
        valid_boards = boards.copy()
        
        num_removed = 0
        
        # step through each of the avaliable boards
        for i, b in enumerate(boards):
            
            # update score card if number is called 
            b.update_scoreboard(n)

            # check if a row or column has been filled (i.e., sum ==5)
            if b.is_winner():
                
                # if it is the last board
                if len(boards) == 1:
                    print("Final winner found after number ", n)
                    print(b.data)
                    print(b.marked)
                    print("Final Score:", b.final_score(n))
                    return(b.final_score(n))
                
                # if it is not the last board
                if len(boards) > 1:
                    #print(b.data)
                    #print(i)
                    print("winner found after number ", n)
                    print(b.data)
                    print(b.marked)
                    print("Final Score:", b.final_score(n))
                    print(i)
                    print(len(valid_boards))
                    valid_boards.pop(i-num_removed)  # THIS WAS THE ISSUE WHEN BOTH LISTS REFERENCE EACH OTHER                 
                    num_removed+=1
                    
        boards = valid_boards.copy()


In [15]:
[numbers, boards] = load_boards("day04_data_test.txt")
losing_board(numbers, boards)

winner found after number  24
[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1.]
 [1. 1. 0. 0. 1.]]
Final Score: 4512
2
3
winner found after number  16
[[22 13 17 11  0]
 [ 8  2 23  4 24]
 [21  9 14 16  7]
 [ 6 10  3 18  5]
 [ 1 12 20 15 19]]
[[0. 0. 1. 1. 1.]
 [0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]
Final Score: 2192
0
2
Final winner found after number  13
[[ 3 15  0  2 22]
 [ 9 18 13 17  5]
 [19  8  7 25 23]
 [20 11 10 24  4]
 [14 21 16 12  6]]
[[0. 0. 1. 1. 0.]
 [1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1.]
 [1. 1. 1. 0. 0.]]
Final Score: 1924


1924

In [16]:
[numbers, boards] = load_boards("day04_data.txt")
losing_board(numbers, boards)

winner found after number  48
[[63  3 22  7 10]
 [36 76 14 77 38]
 [48 27 40  9 60]
 [31 56 75 74 78]
 [86 64 71 90 67]]
[[0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0.]
 [1. 1. 1. 1. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Final Score: 44736
41
100
winner found after number  80
[[75 53  9  1 29]
 [92 94 41 82 38]
 [39 70 80 11 56]
 [64 28 27 22 60]
 [66 97 48 65 71]]
[[1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 1.]
 [0. 0. 1. 0. 0.]]
Final Score: 69520
20
99
winner found after number  95
[[ 0 45 43 79 25]
 [41 10 95 86 80]
 [ 4 60 82 33 75]
 [44 46 38 17 76]
 [22 58 27 73 66]]
[[1. 0. 1. 1. 0.]
 [1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
Final Score: 56620
81
98
winner found after number  95
[[16 27 31 88 86]
 [29 40 65 68 39]
 [15 95 93 69 22]
 [66 48 18 84 11]
 [ 7 51 92 96 99]]
[[1. 1. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
Final Score: 83980
95
97
winner found after number  11
[[44 60 52  7 38]
 [3

 [1. 0. 0. 1. 1.]]
Final Score: 299
23
23
winner found after number  92
[[49 55 93 57  2]
 [67 12 81 70 79]
 [60 44 94 23 54]
 [48 92 99  1 82]
 [76 36 62 32 98]]
[[0. 1. 1. 0. 0.]
 [0. 1. 0. 1. 1.]
 [1. 1. 0. 0. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 0. 1. 1.]]
Final Score: 49128
6
22
winner found after number  92
[[92  1 49 65 77]
 [85  8 27 87 84]
 [41 73 81 15 58]
 [14 93 33 17 52]
 [35 90 37 38  0]]
[[1. 1. 0. 1. 1.]
 [1. 0. 1. 0. 1.]
 [1. 0. 0. 1. 1.]
 [1. 1. 1. 1. 0.]
 [1. 0. 1. 0. 1.]]
Final Score: 43976
14
21
winner found after number  23
[[ 4 95 84 51 36]
 [43 40 37 23 85]
 [14 90  8 59 99]
 [ 0 88 68 93 81]
 [25  6 55 19 48]]
[[0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 0.]
 [1. 1. 1. 1. 0.]
 [0. 1. 1. 0. 1.]]
Final Score: 7498
1
20
winner found after number  23
[[38 23 97 73 35]
 [51 31 90 98 80]
 [56 44 60  8  7]
 [71 10 87  0 99]
 [64 30 20 22 18]]
[[0. 1. 0. 0. 1.]
 [1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 0.]
 [1. 1. 0. 1. 0.]
 [1. 1. 0. 0. 1.]]
Final Score: 12443
9
19
winner found a

1827