In [1]:
import numpy as np

In [2]:
def load_input(path):
    
    file = open(path,'r')
    
    states = []
    xranges = []
    yranges = []
    zranges = []
    
    
    for index, line in enumerate(file.readlines()):
        state, rest = line.split()
        
        x, y, z = rest.split(',')
        x0, x1 = x[2:].split('..')
        xrange = range(int(x0), int(x1)+1)
        y0, y1 = y[2:].split('..')
        yrange = range(int(y0), int(y1)+1)
        z0, z1 = z[2:].split('..')
        zrange = range(int(z0), int(z1)+1)
    
        states.append(state)
        xranges.append(xrange)
        yranges.append(yrange)
        zranges.append(zrange)
        
    return states, xranges, yranges, zranges

In [4]:
states, xranges, yranges, zranges = load_input("day22_data_test_1.txt")

In [5]:
print(states, xranges, yranges, zranges)

['on', 'on', 'on', 'on', 'on', 'on', 'on', 'on', 'on', 'on', 'off', 'on', 'off', 'on', 'off', 'on', 'off', 'on', 'off', 'on', 'on', 'on'] [range(-20, 27), range(-20, 34), range(-22, 29), range(-46, 8), range(-49, 2), range(2, 48), range(-27, 24), range(-39, 6), range(-30, 22), range(-22, 27), range(-48, -31), range(-12, 36), range(-48, -31), range(-18, 27), range(-40, -21), range(-16, 36), range(-32, -22), range(-49, -4), range(18, 31), range(-41, 10), range(-54112, -39297), range(967, 23433)] [range(-36, 18), range(-21, 24), range(-29, 24), range(-6, 47), range(-3, 47), range(-22, 23), range(-28, 27), range(-6, 48), range(-8, 44), range(-27, 21), range(26, 42), range(6, 51), range(-32, -15), range(-33, 16), range(-38, -27), range(-41, 11), range(11, 31), range(-3, 46), range(-20, -7), range(-7, 44), range(-85059, -49292), range(45373, 81176)] [range(-47, 8), range(-26, 29), range(-38, 17), range(-50, 0), range(-24, 29), range(-23, 28), range(-21, 30), range(-3, 45), range(-13, 35), ra

In [6]:
reactor = np.ndarray([101,101,101])

In [7]:
print(reactor[1:5,1:14,10:20])

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0

In [8]:
import math

def intersection(cube1, cube2):
    xb1, yb1, zb1 = cube1
    xb2, yb2, zb2 = cube2
    for a, b in zip(cube1, cube2):
        if a[0] > b[1] or a[1] < b[0]:
            return None

    return tuple((max(a[0], b[0]), min(a[1], b[1])) for a, b in zip(cube1, cube2))

def difference(cube1, cube2):
    int = intersection(cube1, cube2)
    if not int:
        return [cube1]
    new_cubes = []
    new_cubes.append((cube1[0], cube1[1], (cube1[2][0], int[2][0] - 1)))
    new_cubes.append((cube1[0], cube1[1], (int[2][1] + 1, cube1[2][1])))
    new_cubes.append(((cube1[0][0], int[0][0] - 1), cube1[1], int[2]))
    new_cubes.append(((int[0][1] + 1, cube1[0][1]), cube1[1], int[2]))
    new_cubes.append((int[0], (cube1[1][0], int[1][0] - 1), int[2]))
    new_cubes.append((int[0], (int[1][1] + 1, cube1[1][1]), int[2]))

    return [(x, y, z) for x, y, z in new_cubes if x[0] <= x[1] and y[0] <= y[1] and z[0] <= z[1]]

with open('day22_data.txt') as fid:
    lines = []
    for line in fid:
        s = line.strip()
        onoff = s.split()[0]
        bounds = [[int(x) for x in s.split()[1].split(',')[i].split('=')[1].split('..')] for i in range(3)]
        lines.append((onoff, *bounds))

cubes = []
for line in lines:
    onoff = line[0]
    this_cube = line[1:]
    new_cubes = []
    for cube in cubes:
        new_cubes.extend(difference(cube, this_cube))
    if onoff == 'on':
        new_cubes.append(this_cube)
    cubes = new_cubes

print(len(cubes))

s1 = s2 = 0
for cube in cubes:
    s1 += math.prod(max(0, min(50, cube[i][1]) - max(-50, cube[i][0]) + 1) for i in range(3))
    s2 += math.prod(cube[i][1] - cube[i][0] + 1 for i in range(3))
print(s1)
print(s2)


3604
611378
1214313344725528


In [9]:
print(cubes)

[((-39, -38), (-35, -25), (-14, -13)), ((-39, -38), (-35, -25), (-12, -5)), ((-39, -9), (7, 13), (36, 36)), ((-39, -13), (7, 13), (35, 35)), ((-39, -19), (7, 13), (32, 34)), ((-39, -27), (7, 13), (22, 31)), ((-26, -19), (10, 13), (22, 31)), ((-39, -3), [-43, 6], (38, 42)), ((-39, -9), [-43, 6], (36, 37)), ((-8, -3), (-43, -20), (36, 37)), ((-39, -13), [-43, 6], (35, 35)), ((-12, -9), (-43, -8), (35, 35)), ((-8, -3), (-43, -20), (35, 35)), ((-2, 12), (-43, -15), (38, 42)), ((-2, 12), (-43, -20), (35, 37)), ((-39, -19), [-43, 6], (32, 34)), ((-39, -27), [-43, 6], (22, 31)), ((-26, -19), (-43, -38), (22, 31)), ((-39, -27), (-43, -25), (7, 21)), ((-26, -19), (-43, -38), (7, 21)), ((-39, -38), (-43, -25), (6, 6)), ((-37, -19), (-43, -38), (6, 6)), ((-39, -38), (-43, -25), (-4, 5)), ((-37, -35), (-43, -38), (-4, 5)), ((-34, -19), (-43, -38), (-4, 5)), ((-18, -6), (-43, -25), (32, 34)), ((-18, -6), (-43, -38), (7, 31)), ((-5, 12), (-43, -35), (32, 34)), ((-5, 12), (-43, -38), (7, 31)), ((-18,